# Generated by Django 4.1.7 on 2023-03-31 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentos',
            name='data',
            field=models.DateField(verbose_name=datetime.datetime(2023, 3, 31, 17, 30, 57, 625982)),
        ),
    ]
